[package]
name = "mech-notebook"
version = "0.1.0"
authors = ["Corey Montella <corey@mech-lang.org>"]
description = "Gui notebook interface for the Mech programming language."
documentation = "http://docs.mech-lang.org"
homepage = "https://mech-lang.org"
repository = "https://github.com/mech-lang/notebook"
keywords = ["mech", "language", "programming", "dataflow", "runtime"]
categories = ["science::robotics", "science", "game-engines", "web-programming"]
license = "Apache-2.0"
readme = "README.md"
edition = "2021"

[badges]
gitlab = { repository = "mech-lang/notebook", branch = "main" }
maintenance = { status = "actively-developed" }

[dependencies]
mech-core = "0.1"
mech-utilities = "0.1"
mech-syntax = "0.1"
mech-gui = "0.1"

lazy_static = "1.4.0"
eframe = { version = "0.18.0"}
image = { version = "0.24.3", default-features = false, features = [
  "ico",
  "jpeg",
  "png",
] }

tracing-subscriber = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
tracing-wasm = "0.2.1"

[workspace]

[build-dependencies]
winres = "0.1.12"

[package.metadata.winres]
OriginalFilename = "MECH.EXE"
LegalCopyright = "Copyright © 2023"