[package]
name = "mech-notebook"
version = "0.1.0"
authors = ["Corey Montella <corey@mech-lang.org>"]
license = "Apache-2.0"
edition = "2021"
build = "build.rs"

[badges]
gitlab = { repository = "mech-lang/notebook", branch = "main" }
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
all-features = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
mech-core = {git = "https://gitlab.com/mech-lang/core", branch = "v0.1-beta"}
mech-utilities = {git = "https://gitlab.com/mech-lang/utilities", branch = "v0.1-beta"}
mech-syntax = {git = "https://gitlab.com/mech-lang/syntax", branch = "v0.1-beta"}
mech-gui = {git = "https://gitlab.com/mech-lang/machines/gui", branch = "v0.1-beta"}

lazy_static = "1.4.0"
eframe = { version = "0.18.0"}
image = { version = "0.24.3", default-features = false, features = [
  "ico",
  "jpeg",
  "png",
] }

tracing-subscriber = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
tracing-wasm = "0.2.1"

[build-dependencies]
winres = "0.1.12"

[package.metadata.winres]
OriginalFilename = "MECH.EXE"
LegalCopyright = "Copyright © 2022"

[workspace]